dom0/qvm-tools: output diagnostics to stderr instead of stdout (#276)

diff --git a/dom0/qvm-tools/qvm-sync-dom0-clock b/dom0/qvm-tools/qvm-sync-dom0-clock
--- a/dom0/qvm-tools/qvm-sync-dom0-clock
+++ b/dom0/qvm-tools/qvm-sync-dom0-clock
@@ -10,7 +10,7 @@ if [ -z "$CLOCK_VM" ]; then
 fi
 
 if ! xl domid "$CLOCK_VM" > /dev/null 2>&1; then
-    echo "ClockVM not started, exiting!"
+    echo "ClockVM not started, exiting!" >&2
     exit 1
 fi
 
@@ -27,8 +27,8 @@ CURRENT_TIME="$($QREXEC_CLIENT -d $CLOCK_VM 'user:date -u' |
 if [ -n "$CURRENT_TIME" ] ; then 
 	echo Syncing Dom0 clock: setting time "$CURRENT_TIME"...
 	sudo date -u -s "$CURRENT_TIME" ;
-	echo Done.
+	echo Done. >&2
 else
-	echo "Error while parsing the time obtained from the ClockVM ($CLOCK_VM).."
+	echo "Error while parsing the time obtained from the ClockVM ($CLOCK_VM).." >&2
 fi
 
