Autocommit template changes after template shutdown (#96)

diff --git a/common/block-snapshot b/common/block-snapshot
--- a/common/block-snapshot
+++ b/common/block-snapshot
@@ -174,6 +174,12 @@ case "$command" in
               dmsetup remove $snap
             fi
           done
+          # Commit template changes
+          domain=$(xenstore_read "$XENBUS_PATH/domain")
+          if [ "$domain" ]; then
+            # Dont stop on errors
+            /usr/bin/qvm-template-commit "$domain" || true
+          fi
         fi
 	
         if [ -e $node ]; then
